### ISSUE TITLE
Where is the source of the support package?

### ISSUE THREAD

**Issue by JL2210** [avast-tl/retdec-support#5]
At the end of the install process of RetDec, I noticed my computer was downloading a large amount of data. I looked and saw that it was downloading a release package from this GitHub repository, and looked to see if I could build it myself. Lo and behold, the only available downloads are pre-packaged from the Releases section. Is it possible to include the source in this repo?

**Comment by s3rvac** [comment]
Hi. Since 2019-03-08, the [release package](https://github.com/avast/retdec-support/releases/download/2019-03-08/retdec-support_2019-03-08.tar.xz) contains only source files, no binary blobs. So, if you want the sources, you can just download and unpack the package (`tar.xz` archive).

> Is it possible to include the source in this repo?

In theory, this would be possible, but the sources have over 700 MB (and can change rapidly over time), so we have decided against putting them into version control and provide them only in form of a release. Even GitHub itself recommends repositories to be kept under 1 GB. Nevertheless, we may decide to put the sources into the repository in the future, but for now, you will have to download and unpack the release package.
